name: commit-lint
 
on: [push, pull_request, pull_request_target]
 
jobs:
  lint:
    runs-on: ubuntu-latest
 
    steps:
      - name: Validate conventional commits
          uses: ahmadnassri/action-commit-lint@v2.1.17
    